name: Build and deploy to Github pages

on:
  push:
    branches:
      - main
      - 'test/token'
      - '*/*'
    tags:
      - "*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@v3.0.0
      - name: Print secret
        run: "echo $GITHUB_TOKEN"
