name: Build and deploy

on:
  push:
    branches:
      - main
      - fix/gh-pages
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/fix/gh-pages'
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.14.1
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
