name: Linting

on:
  - pull_request
  - push

jobs:
  build:
    name: Run ESLint & Stylelint
    runs-on: ubuntu-latest
    steps:
      
      # Check out the repository
      - uses: actions/checkout@v2

      # Install Node.js
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      # Install your dependencies
      - run: npm ci

      # Run ESLint
      - uses: eslint/github-action@v0
      
      # Run Stylelint
      # https://github.com/actions-hub/stylelint/issues/8
      - uses: actions-hub/stylelint@f7f2ea6
